name: SonarQube Analysis & Quality Gate Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: SonarQube Scanner Setup
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        token: ${{ secrets.SONAR_TOKEN }}

    - name: Run SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    
    - name: Fetch SonarQube Quality Gate and Project Details
      id: sonar-details
      run: |
        curl -u ${{ secrets.SONAR_TOKEN }} -X GET "http://localhost:9000/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" > quality_gate.json
        curl -u ${{ secrets.SONAR_TOKEN }} -X GET "http://localhost:9000/api/issues/search?componentKeys=${{ secrets.SONAR_PROJECT_KEY }}" > issues.json
        curl -u ${{ secrets.SONAR_TOKEN }} -X GET "http://localhost:9000/api/measures/component?component=${{ secrets.SONAR_PROJECT_KEY }}&metricKeys=bugs,vulnerabilities,code_smells,duplicated_lines,coverage" > metrics.json

    - name: Generate PDF Report
      run: |
        python generate_sonarqube_report.py
